AWSTemplateFormatVersion: '2010-09-09'
Description: ALB arch for testing
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: test-web
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  SiteDomain:
    Type: String
    AllowedPattern: (?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]
    Description: Website domain

Resources:
  TestApCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref SiteDomain
      ValidationMethod: DNS
  TestApVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.11.0.0/20
      EnableDnsHostnames: true
  TestApIGW:
    Type: AWS::EC2::InternetGateway
  AttachTestApIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref TestApIGW
      VpcId: !Ref TestApVPC

  # EIP
  TestApEIP1:
    Type: AWS::EC2::EIP
  AssociateTestEIP1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt TestApEIP1.AllocationId
      InstanceId: !Ref TestApInstanceA
  TestApEIP2:
    Type: AWS::EC2::EIP
  AssociateTestEIP2:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt TestApEIP2.AllocationId
      InstanceId: !Ref TestApInstanceC
  TestApEIP3:
    Type: AWS::EC2::EIP
  AssociateTestEIP3:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt TestApEIP3.AllocationId
      InstanceId: !Ref TestApInstanceD

  # Security Group
  TestApSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Target instance Security group
      VpcId: !Ref TestApVPC
      SecurityGroupIngress:
        - CidrIp: !GetAtt TestApVPC.CidrBlock
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: !GetAtt TestApVPC.CidrBlock
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: !GetAtt TestApVPC.CidrBlock
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - SourceSecurityGroupId: !Ref TestALBSG
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
  TestALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security group
      VpcId: !Ref TestApVPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443

  # Subnet
  TestApSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.11.1.0/24
      VpcId: !Ref TestApVPC
  TestApSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.11.2.0/24
      VpcId: !Ref TestApVPC
  TestApSubnetD:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.11.3.0/24
      VpcId: !Ref TestApVPC

  # Routing
  TestIGWRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TestApVPC
  TestIGWRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref TestIGWRouteTable
      GatewayId: !Ref TestApIGW
      DestinationCidrBlock: 0.0.0.0/0

  AssociateTestIGW1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TestIGWRouteTable
      SubnetId: !Ref TestApSubnetA
  AssociateTestIGW2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TestIGWRouteTable
      SubnetId: !Ref TestApSubnetC
  AssociateTestIGW3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TestIGWRouteTable
      SubnetId: !Ref TestApSubnetD

  # EC2 Template
  TestApEc2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: sample-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        UserData: !Base64
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - yum update -y
              - amazon-linux-extras install -y lamp-mariadb10.2-php7.3 php7.3
              - yum install -y httpd mariadb-server
              - systemctl start httpd
              - systemctl enable httpd
              - usermod -a -G apache ec2-user
              - chown -R ec2-user:apache /var/www
              - chmod 2775 /var/www
              - find /var/www -type d -exec chmod 2775 {} \;
              - find /var/www -type f -exec chmod 0664 {} \;
              - echo "Hello World" > /var/www/html/index.php

  TestApInstanceA:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref TestApSubnetA
      SecurityGroupIds:
        - !GetAtt TestApSG.GroupId
      LaunchTemplate:
        LaunchTemplateId: !Ref TestApEc2LaunchTemplate
        Version: !GetAtt TestApEc2LaunchTemplate.LatestVersionNumber
  TestApInstanceC:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref TestApSubnetC
      SecurityGroupIds:
        - !GetAtt TestApSG.GroupId
      LaunchTemplate:
        LaunchTemplateId: !Ref TestApEc2LaunchTemplate
        Version: !GetAtt TestApEc2LaunchTemplate.LatestVersionNumber
  TestApInstanceD:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref TestApSubnetD
      SecurityGroupIds:
        - !GetAtt TestApSG.GroupId
      LaunchTemplate:
        LaunchTemplateId: !Ref TestApEc2LaunchTemplate
        Version: !GetAtt TestApEc2LaunchTemplate.LatestVersionNumber

  # Application Load Balancing
  TestApALBTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: test-ap-alb-target
      Port: 80
      Protocol: HTTP
      VpcId: !Ref TestApVPC
      HealthCheckPath: /index.php
      Targets:
        - Id: !Ref TestApInstanceA
          Port: 80
        - Id: !Ref TestApInstanceC
          Port: 80
        - Id: !Ref TestApInstanceD
          Port: 80
  TestApALBFrontListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Host: '#{host}'
            Path: '/#{path}'
            Port: '443'
            Protocol: HTTPS
            Query: '#{query}'
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref TestApALB
      Port: 80
      Protocol: HTTP
  TestApALBSSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TestApALBTarget
      Certificates:
        - CertificateArn: !Ref TestApCertificate
      LoadBalancerArn: !Ref TestApALB
      Port: 443
      Protocol: HTTPS
  TestApALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: test-ap-alb
      LoadBalancerAttributes:
        - Key: routing.http2.enabled
          Value: 'false'
      SecurityGroups:
        - !Ref TestALBSG
      Subnets:
        - !Ref TestApSubnetA
        - !Ref TestApSubnetC
        - !Ref TestApSubnetD

Outputs:
  VPC:
    Value: !Ref TestApVPC
  SubnetA:
    Value: !Ref TestApSubnetA
  SubnetC:
    Value: !Ref TestApSubnetC
  SubnetD:
    Value: !Ref TestApSubnetD