#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;
use AlbCFn\Cli\Command\{
    CreateStackCommand, UpdateStackCommand, DeleteStackCommand
};
use AlbCFn\Cli\Command\Equipment\{InitSSMStackCommand, PrepareEC2StackCommand};
use AlbCFn\Cli\Command\Concerns\{SubOptions, TargetArguments};

$env = new Dotenv();
$env->load(__DIR__.'/../.env');

$application = new Application();

$application->addCommands([
    new CreateStackCommand(new TargetArguments),
    new UpdateStackCommand(new TargetArguments),
    new DeleteStackCommand(new TargetArguments),
    new InitSSMStackCommand(new SubOptions),
    new PrepareEC2StackCommand(new SubOptions)
]);

$application->run();
